### ISSUE TITLE
feature request/suggestion:   nilearn-type mechanism for accessing online datasets

### ISSUE THREAD

**Issue by JohnGriffiths** [the-virtual-brain/tvb-data#1]
NiLearn has IMHO an excellent mechanism for downloading online datasets for exploratory analysis. 

http://nilearn.github.io/building_blocks/pipeline_introduction.html#data-loading

Since a current aim is for the tvb developers and community to assemble a database of simulation results and tvb-prepped datasets (which obviously can't all live in this github repo), I think something like this would be very handy to have in the code base at some point.

**Comment by maedoc** [comment]
on JIRA http://req.thevirtualbrain.org/browse/TVB-2007
